### PR TITLE
fix patching of nested structs

### LINKED ISSUE #21: Nested Structs
If I understand this correctly, struct-patch does not support nested structs? i.e. if I have a patched struct that depends on another patched struct, the derived serde code references the original struct instead of the patched version.

Is this correct, is there some way to override this or are you planning on adding this feature?

### PR DESCRIPTION
**Pull request by mirosval**
when nesting structs, the patches should also use nested patches instead of the original nested structs, otherwise a patch with a nested structure can not be deserialized from json (the original non-patched struct is used to deserialize the json and if fields are missing, it fails)

this pr solves the problem by introducing #[patch_name = <name>] attribute that can be added to fields. The name should point to the patch structure that should be used instead of the original. This attribute then causes 2 things to happen:
1. The new name is used for the type of the field in generated code
2. It generates different methods in the Patch traits based on if the fields are renamed or not

This should fix #21

### CODE REVIEW

File: struct-patch-derive/src/lib.rs [hunk 1]
```diff
@@ -111,18 +111,68 @@ pub fn derive_patch(item: TokenStream) -> TokenStream {
...
+                    })
+                    .map(|syn::Attribute { meta, .. }| match meta {
+                        Meta::NameValue(MetaNameValue {
+                            path: _,
+                            value: Expr::Lit(lit, ..),
+                            ..
+                        }) => {
+                            if let Lit::Str(l) = &lit.lit {
+                                let ident = Some(Ident::new(
+                                    l.value().to_string().trim_matches('"'),
```
Comment (yanganto) [inline struct-patch-derive/src/lib.rs:135]:
```suggestion
                                    l.value().trim_matches('"'),
```

**Review by yanganto — APPROVED** [review]
Awesome.  Just a little lint issue needs your hand.
